select * from EMPLOYEES;

select * from EMPLOYEES where SALARY=(select max(SALARY)from EMPLOYEES);

SELECT * FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES
   WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES));

SELECT * FROM EMPLOYEES WHERE SALARY > (SELECT avg(SALARY) FROM EMPLOYEES);
